<?php

namespace app\modules\catalog\controllers;
use app\assets\CatalogAsset;
use app\modules\catalog\models\Lists;
use app\modules\catalog\models\ListsGoods;
use app\modules\catalog\models\TagsGroups;
use app\modules\common\controllers\FrontController;
use app\modules\common\models\Zloradnij;

/**
 * ActionsController implements the CRUD actions for Actions model.
 */
class ProductListController extends FrontController
{
    public function init()
    {
        CatalogAsset::register($this->view);
        $this->view->registerCssFile('/css/lists.css');
        $this->view->registerJsFile('/js/catalog-list.js', ['depends' => [\yii\web\JqueryAsset::className()]]);

        return parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Lists all Actions models.
     * @return mixed
     */
//    public function actionIndex()
//    {
//        $searchModel = new ActionsSearch();
//        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
//
//        return $this->render('index', [
//            'searchModel' => $searchModel,
//            'dataProvider' => $dataProvider,
//        ]);
//    }

    /**
     * Lists all Actions models.
     * @return mixed
     */
    public function actionView($id)
    {

        $list = Lists::findOne($id);
        if(empty(\Yii::$app->session['catalog']['product-list'][$id])){
            $list->removeOldProducts();
            $list->setSessionList();
        }
        $products = $list->getSessionList();

        return $this->render('view', [
            'model' => $list,
            'products' => $products,
            'activeTagsGroups' => TagsGroups::find()->where(['status' => 1,'show' => 1,'type' => 1])->indexBy('id')->all(),
        ]);
    }
}