<?php

namespace app\components;

use app\modules\basket\models\BasketOne;
use yii\base\Widget;
use app\modules\common\models\UserShop;
use app\modules\common\models\ModFunctions;
use Yii;

class WPaymentSelectMy extends Widget{
    public $basket;
    public $sort = 4;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run(){
        $this->basket = \Yii::$app->basket->getBasket();
        $currentUser = \Yii::$app->basket->getCurrentUser();
//        Zloradnij::print_arr($this->basket);die();
        $userCards = \Yii::$app->basket->getCurrentUserCards();

        $surcharge = false;

        // Флаг для вывода доплаты вместо оплаты с банковской карты;
        $resultPrise = $this->basket->delivery_price + $this->basket->priceDiscount;
        if ($resultPrise > 0) {
            $check_money = $resultPrise - $currentUser->money;
            if ($check_money > 0) {
                $surcharge = $check_money;
            }
        }

        $formHtml = '
       <!--Оплата-->
        <div id="basket-page-payments" class="my-payments">';

        foreach($userCards as $i => $card){
            $formHtml .= '
                    <div class="item radio">
                        <input type="hidden" name="card_id" value="'.$i.'" />
                     <label class="radio__label">
                        <input id="payment-3-'.$i.'" type="radio" name="payment_id" value="3"'.(($this->basket->payment_id == 3)?' checked':'').' class="radio" />

                        ';
            if($surcharge > 0){
                $formHtml .= '
                             <span class="radio-checked"'.Yii::t("app","Доплатить с сохраненной банковской карты").' ('.$surcharge.'<small class="rubznak">p.</small>) '.$card['card_number'].' &nbsp; <a href="/" class="dotted" onclick="return delete_card('.$i.');">'.Yii::t('app','удалить').'</a></span>';
            }else{
                $formHtml .= '
                             <span class="radio-checked">'.Yii::t("app","Оплата с сохраненной банковской карты").$card['card_number'].'&nbsp; <a href="/" class="dotted" onclick="return delete_card('.$i.');">'.Yii::t('app','удалить').'</a></span>';
            }
            $formHtml .= '
                             <div class="description-min">'.Yii::t('app','Денежные средства спишутся со счета сохраненной банковской карты.').'</div>
                      </label>
                    </div>';
        }

        $formHtml .= '
        <div class="item radio" data-q="2">';
        $formHtml .= '
                 <label class="radio__label">
                    <input id="payment-2" type="radio" name="payment_id" value="2"'.(($this->basket->payment_id == 2)?' checked':'').((!$currentUser->money)?' checked':'').' class="radio" />';
        if($surcharge > 0) {
            $formHtml .= '
                     <span class="radio-checked" >'.Yii::t('app','Доплатить с банковской карты').'('.$surcharge.' <small class="rubznak">p.</small>)</span >';
        }else{
            $formHtml .= '
                      <span class="radio-checked" >'.Yii::t('app','Оплата с банковской карты').'</span >';
        }
        $formHtml .= '
                    <div class="description-min">'.Yii::t('app','Денежные средства спишутся со счета банковской карты.').'</div>
                    <!--Сохранения карта-->
                    <div class="checkbox hidden"><label><input type="checkbox" class="check" value="1" name="save_card">'.Yii::t('app','Запомнить данные моей карты для будущих платежей').'<div class="form-links"><a target="_blank" href="http://www.esalad.ru/static/page/rules#payment">'.Yii::t('app','Правила привязки карты').'</a></div></label></div>
                    <!--/Сохранения карта-->
                 </label> ';
        $formHtml .= '
            </div>';
        $formHtml .= '
      </div>';
        return $formHtml;
    }
}
