<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\assets;

use app\modules\common\models\Zloradnij;
use yii\web\AssetBundle;

/**
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class AppAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css = [
        'css/styles.css',
        'css/my.css',
        'css/global.css',
        'css/shop-management/shop.css',
        'css/shop-management/cms.css',
    ];
    public $js = [
        'js/config.js',
        'js/shop.js',
        'js/catalog.js',
        'js/global.js',
        'js/shop-management/dropzone.js',
        'js/shop-management/shopStatistic.js',
        'scripts/jquery.zoom.js',
        'scripts/jquery.calendar.js',
        'scripts/jquery.date.js',
        'scripts/jquery-ui.min.js',
        'js/shop-management/cms.js',
        'js/shop-management/manager.js',
        'js/shop-management/shopScripts.js',
    ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
