<?php
/**
 * @link http://zloradnij.ru/
 * @copyright Copyright (c) 2015 Studio 90-is
 * @license http://zloradnij.ru/license/
 */

namespace app\assets;

use yii\web\AssetBundle;

class BasketAsset extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $css;
    public $js;
    public function init()
    {
        // Стиль
        $this->css = [
            'css/styles.css',
            'css/my.css',
            'css/shop-management/jquery-ui.min.css',
            'css/basket.css?'.time(),
            'css/global.css?'.time(),
            'css/screen.css?'.time(),
            'css/green_styles.css',
        ];
        // Сайт;
        $this->js = [
            'js/config.js',
            'js/shop.js?'.time(),
            'https://api-maps.yandex.ru/2.1/?lang=ru_RU',
//        '/js/callback.js',
            '/js/polygon.js',
            '/js/basket.js?'.time(),
            '/js/global.js?'.time(),
            'js/mobile.js?'.time(),
            '/js/callback.zloradnij.js?'.time(),
            'scripts/progressbar.js',
            'scripts/slider/slider.js',
            'scripts/jquery.date.js',
            'scripts/jquery.zoom.js',
            'scripts/jquery.custom.js',
            'scripts/progressbar.js',
            'scripts/touch-zoom.js',
        ];
        parent::init(); // TODO: Change the autogenerated stub

    }

    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapAsset',
    ];

}